
CAMERA_TYPE="MOCK"
CAMERA_INDEX = 0  # used for 'WEBCAM' and 'CVCAM' when there is more than one camera connected 
DRIVE_TRAIN_TYPE = "VESC"
VESC_MAX_SPEED_PERCENT =.2 ## Max speed as a percent of actual max speed 
VESC_SERIAL_PORT= "/dev/ttyACM0" ## check this val with ls /dev/tty* 
VESC_HAS_SENSOR= True 
VESC_START_HEARTBEAT= True 
VESC_BAUDRATE= 115200 
VESC_TIMEOUT= 0.05 
VESC_STEERING_SCALE = .5
VESC_STEERING_OFFSET = .5
DONKEY_GYM = False

USE_JOYSTICK_AS_DEFAULT = True      #when starting the manage.py, when True, will not require a --js option to use the joystick
JOYSTICK_MAX_THROTTLE = 0.6         #this scalar is multiplied with the -1 to 1 throttle value to limit the maximum throttle. This can help if you drop the controller or just don't need the full speed available.
JOYSTICK_STEERING_SCALE = 1.0       #some people want a sateering that is less sensitve. This scalar is multiplied with the steering -1 to 1. It can be negative to reverse dir.
AUTO_RECORD_ON_THROTTLE = False      #if true, we will record whenever throttle is not zero. if false, you must manually toggle recording with some other trigger. Usually circle button on joystick.
CONTROLLER_TYPE = 'F710'            #(ps3|ps4|xbox|pigpio_rc|nimbus|wiiu|F710|rc3|MM1|custom) custom will run the my_joystick.py controller written by the `donkey createjs` command
PATH_SCALE = 25.0                    # the path display will be scaled by this factor in the web page
PATH_OFFSET = (0, 0)                # 255, 255 is the center of the map. This offset controls where the origin is displayed.
PATH_MIN_DIST = 0.01                 # after travelling this distance (m), save a path point
PID_P = 0.03                   # proportional mult for PID path followe
PID_I = 0.0                       # integral mul:w for PID path follower
PID_D = 0.15                     # differential mult for PID path follower
PID_THROTTLE = 0.3                  # constant throttle value during path following
GPS_SERIAL="/dev/ttyUSB2"
GPS_SERIAL_BAUDRATE = 38400 #ublox
GPS_DEBUG = True
# HAVE_GPS = True
HAVE_GPS = False
GPS_NMEA_PATH = None
SAVE_PATH_BTN = "Y"    	# button to save path
LOAD_PATH_BTN = "X"         	# button (re)load path
RESET_ORIGIN_BTN = "B" 	# button to press to move car back to origin
ERASE_PATH_BTN = None 	# button to erase path
TOGGLE_RECORDING_BTN = "A" # button to toggle recording mode
INC_PID_D_BTN = None        	# button to change PID 'D' constant by PID_D_DELTA
DEC_PID_D_BTN = None        	# button to change PID 'D' constant by -PID_D_DELTA
INC_PID_P_BTN = None        	# button to change PID 'P' constant by PID_P_DELTA
DEC_PID_P_BTN = None        	# button to change PID 'P' constant by -PID_P_DELTA
PATH_SEARCH_LENGTH = 10   # number of points to search for closest point, None to search entire path
PATH_LOOK_AHEAD = 4         # number of points ahead of the closest point to include in cte track
PATH_LOOK_BEHIND = 4        # number of points behind the closest point to include in cte track   
PID_D_DELTA = 0.1
PID_P_DELTA = 0.1
ESP32_PORT1 = "/dev/ttyUSB0"
ESP32_PORT2 = "/dev/ttyUSB1"
IMU_PORT = "/dev/ttyACM1"
QUEUE_SIZE = 10
# ANCHOR_DISTANCE = 0.37
ANCHOR_DISTANCE = 0.71
PLOT_LIMIT_FACTOR = 10.0
REFRESH_RATE = 0.01
BAUD_RATE = 115200
WAYPOINTS_PER_METER = 10
DISTANCE_THRESHOLD = 10.0
PID_THROTTLE_DECELERATE = 0.1 # Percentage of the waypoints to decelerate when the path is reaching completion.
PATH_CURVE_FACTOR = 1.5 # Use this to control the curvature of the path. Higher values mean lower curvature.
